# Site settings
title: Education
email: youremailaddress@gmail.com
description: Cloud4est
baseurl: "/site_education" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# Misc settings
featured-image-source:

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/Cloud4est/
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
